# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc5060d7d442c79b5d1a0df187c1b6ee9e204285cfe5333fcd7b13ef37f18d66d044717805578e40e4b174f58927772510df4c6b6f421e2540417a00a730b415

test:
  secret_key_base: ae07d92dfbf100ac051e1e219c79622dbd3d5bf87360a8b24cd1e5c002ec60e81879cda217db8b545a4bcf7e9b1b70f18bfa56b6744c14e8dbc9967786616015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
